### ISSUE TITLE
[Thieving] Stalls

### ISSUE THREAD

**Issue by CloudS3c** [AlterRSPS/Alter#49]
Unsure but just tested it and some of the stall's don't work
![image](https://user-images.githubusercontent.com/50030246/185742172-6a904920-e9c0-41c4-807b-cd575d355a7e.png)

_Originally posted by @CloudS3c in https://github.com/AlterRSPS/Alter/issues/48#issuecomment-1221276701_

**Comment by KevinSenez** [comment]
Works fine for me, as shown here:
![image](https://user-images.githubusercontent.com/3402296/185762746-0b70092a-8e79-41e2-a734-395c6e4e09d6.png)
