### ISSUE TITLE
on_item_on_npc not working

### ISSUE THREAD

**Issue by starfish671** [AlterRSPS/Alter#64]
Tried using `on_item_on_npc` with the Alter client https://AlterRSPS/Runelite and it looks like the server does not receive the request or the client doesn't respond.

Unsure how to actually debug further.

The method `on_item_on_object` works as intended. My next approach is going to be debugging this to see how it works, but asking here for some insight.

**Comment by CloudS3c** [comment]
Fixed on #1750dac
